defaults:
  - /train/default
  - /env/realant

domain_randomization:
  enabled: false

experiment:
  description: "PPO with custom success-based rewards for calm walking"
  name: ppo_custom_reward

sr2l:
  enabled: false

env:
  name: RealAntMujoco-v0
  use_success_reward: true  # Enable our custom wrapper!

# Keep same hyperparameters as baseline for fair comparison
ppo:
  learning_rate: 0.0003
  ent_coef: 0.0  # Keep same as baseline

# Train for full 10M steps
total_timesteps: 10000000