defaults:
  - /train/default           # Start with normal PPO training
  - /env/realant

# Experiment settings
experiment:
  description: "Full Phased SR2L training - 4M no SR2L + 6M with SR2L"
  name: ppo_sr2l_phased
  tags: 
    - ppo
    - sr2l
    - phased
    - phase3

# Phase 1: Normal PPO training (no SR2L for first 4M steps)
# Phase 2: Enable SR2L for remaining 6M steps
sr2l:
  enabled: true
  lambda: 0.001                   # 10x stronger for better smoothness
  perturbation_std: 0.02          # Slightly larger perturbations
  warmup_steps: 4000000           # No SR2L for first 4M steps
  apply_frequency: 5              # Apply more frequently for stability
  max_perturbation: 0.1           # Allow larger max perturbation

# Environment settings
env:
  name: RealAntMujoco-v0
  use_success_reward: true

# Full 10M training - first 4M pure PPO, last 6M with SR2L
total_timesteps: 10000000

# Enable W&B logging
logging:
  wandb: true
  wandb_project: "robust-quadruped-rl"
  wandb_entity: "anandpatel1221178-university-of-the-witswatersrand"
  verbose: 1